# Fastlane config for STRIDE iOS App

# This is the minimum version number required.
fastlane_version "2.62.0"

default_platform :ios

platform :ios do

  desc "Create a Development build"
    lane :Development do |options|
      gym(
        scheme: options[:scheme],
        export_method: "development"
      )
  end

  desc "Create a Distribution build"
  lane :Distribution do |options|
    gym(
      scheme: options[:scheme],
      export_method: "enterprise"
    )
  end

  after_all do |lane|
    slack(
       message: "iOS build was successful."
    )
    upload_symbols_to_crashlytics(dsym_path: "./Stride.app.dSYM.zip", gsp_path: "./GoogleService-Info.plist")
  end

  error do |lane, exception|
    slack(
       message: exception.message,
       success: false
    )
  end

end
